### ISSUE TITLE
how to train my own coco type datasets?

### ISSUE THREAD

**Issue by RobertTang0** [tgxs002/CORA#14]
CORA: error: argument --coco_path: expected one argument
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 2391479) of binary: /home/root123/.conda/envs/tlb/bin/python
Traceback (most recent call last):
  File "/home/root123/.conda/envs/tlb/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/root123/.conda/envs/tlb/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/root123/.conda/envs/tlb/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-04_02:03:52
  host      : gpu22
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 2391479)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by TaroPlay** [comment]
大佬，搞定了这个问题吗？
